from __future__ import annotations

AUDIT_ACTIONS: tuple[str, ...] = (
    "vault.create",
    "vault.read",
    "vault.update",
    "vault.archive",
    "vault.delete",
    "project.create",
    "project.read",
    "project.update",
    "project.archive",
    "secret.create",
    "secret.read",
    "secret.archive",
    "secret.decrypt",
    "secret.rotate",
    "secret.delete",
    "apikey.create",
    "apikey.read",
    "apikey.update",
    "apikey.revoke",
    "role.create",
    "role.read",
    "role.update",
    "role.assign",
    "role.revoke",
    "profile.update",
    "settings.preferences.update",
    "settings.notifications.update",
    "session.revoke",
    "login.success",
    "login.failure",
    "permission.denied",
)
